version: '3.7'
services:
  web:        
    build: ./docker/apache
    user: "1000"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /opt/data:/var/www/html/src/web/data
    ports:
      - 80:80
